### ISSUE TITLE
Q & A suggestion

### ISSUE THREAD

**Issue by adiapel** [IdoSagiv/CommuniDog#1]
Hi!
I tried to install your project and it was the first time for me to use android studio.
While trying to build and run the project, I encountered the following problem:
"Failed to install the following Android SDK packages as some licenses have not been accepted."
I suggest that you will open a Q&A section in your repository and add my problem with the following solution:
https://stackoverflow.com/questions/39760172/you-have-not-accepted-the-license-agreements-of-the-following-sdk-components
If you would accept my suggestion, I would like later to open a pull request in order to update your README file
which will link to this section for frequency problems & answers during the instllation.

Adi

**Comment by IdoSagiv** [comment]
Hey,
Thank you for your suggestion, I added a [Q&A page](https://github.com/IdoSagiv/CommuniDog/wiki/Q&A) on the project's wiki with your bug. Please open a pull request 
with the suggested readme change and link it to this issue

**Comment by IdoSagiv** [comment]
suggestion added https://github.com/IdoSagiv/CommuniDog/pull/2
