### ISSUE TITLE
when launching the app on the 1st time- its crashing

### ISSUE THREAD

**Issue by eyal1889** [IdoSagiv/CommuniDog#13]
hi, when i launched the app for the 1st time it crashed. 
on the 1st time you launch the app, it asks for a location permission, and then crashes.
after i gave the permission and re-launched it didnt crash and i could proceed after the login screen.

**Comment by eyal1889** [comment]
the problem caused due to the ungave permission, so should check if it wasnt given, and if not then stay in same screen maybe?

**Comment by IdoSagiv** [comment]
Hi,
Thanks for your report, we'll address it and hopefully post a revised version soon
