### ISSUE TITLE
bug in activity_emergency_numbers.xml

### ISSUE THREAD

**Issue by sagi5362** [IdoSagiv/CommuniDog#26]
I'm using a Nexus 5 emulator on my android studio and as you see the layout does not match the size of my device
![emergency_numbers](https://user-images.githubusercontent.com/70053811/122225696-f5a05b80-cebd-11eb-855c-4c108472a15b.png)

**Comment by IdoSagiv** [comment]
fixed by Sagi Dekel [here](https://github.com/IdoSagiv/CommuniDog/pull/27)
