### ISSUE TITLE
[enhancement] Adding support of dark mode.

### ISSUE THREAD

**Issue by ori-frenkel** [IdoSagiv/CommuniDog#65]
# What
Make the app support dark mode - when the user switch his system to dark mode, the application colors should changed accordingly.

# Why
* In recent years, many phone come with an oled display, these displays can shut down pixels (which are black), and by this way able to save battery.
* In addition, many people prefer dark mode themes (feel more comfortable on the eyes, specifically in the night)
* Every polished app support dark mode.

**Comment by IdoSagiv** [comment]
This feature wae already suggested as part of issue #58
