### ISSUE TITLE
[CRITICAL] Insecure user management 

### ISSUE THREAD

**Issue by ScDor** [IdoSagiv/CommuniDog#7]
Hey,

Seems like user data management (sign up, log in) happens with a local copy of the Firebase instance (downloaded, then uploaded with the changes), which raises the following issues:
- All user data, including usernames, unencrypted passwords, **ID numbers** and geolocation is available, unencrypted, for anyone to see by forking the repo and using a breakpoint while logging in.
- Downloading the user list and uploading it may allow users to delete or alter usernames, passwords, or other properties of other (possibly, all) users.
- Two users registering at the same time may cause race conditions, one updating the DB while the other is "ignored"

Suggested solution: 
- Implement [Login with Google](https://developers.google.com/identity/sign-in/android/start-integrating?hl=en), to take care of all signup/logins. 
- That this will require additional changes in saving/retrieving information about users. 
- forked versions of this app are connected to the same DB instance, which may leak user emails (or other details) even after implementing login with google, but that's for a different issue.

Cheers

**Comment by IdoSagiv** [comment]
Hi,
Thanks for your report, we'll address it and hopefully post a revised version soon
